### ISSUE TITLE
Error: unrecognized cop Layout/IndentationStyle found in .rubocop.yml

### ISSUE THREAD

**Issue by codemicky** [rubocop-hq/rubocop#8078] opened 2020-06-01 19:33 UTC
`Layout/IndentationStyle`

Is this renamed or deleted?

**Comment by koic** [comment] 2020-06-02 02:15
The cop has been renamed from `Layout/Tab` to `Layout/IndentationStyle` since RuboCop 0.82.0. https://github.com/rubocop-hq/rubocop/blob/v0.85.0/CHANGELOG.md#changes-3

Are you using RuboCop 0.82.0 or higher? If it is RuboCop 0.81.0 or lower, it's an old name.

**Comment by koic** [comment] 2020-06-11 02:58
I'll close this issue. Please reopen if the problem is not resolved. Thank you.

**Closed by koic** 2020-06-11 02:58 UTC

**Comment by mateusdeap** [comment] 2025-04-17 09:27
I ran into this issue just yesterday. I think the docs aren't clear enough. They mention it was added in version 0.49 and changed in 0.82. Would it be worth it to edit the doc and explain the change was a rename? Or maybe link to the changelog entries giving the cop's history?
