### ISSUE TITLE
Autocorrect of Style/MultilineIfModifier triggers Style/GuardClause

### ISSUE THREAD

**Issue by jcoyne** [rubocop-hq/rubocop#3759] opened 2016-12-01 17:41 UTC
given this code:

```ruby
    def create_transfer_request
      ContentDepositorChangeEventJob.perform_later(self,
                                                   'sample') if on_behalf_of.present?
    end
```

When I scan it I get:
```
Style/MultilineIfModifier: Favor a normal if-statement over a modifier clause in a multiline statement.
      ContentDepositorChangeEventJob.perform_later(self, ...
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If I autocorrect it, it becomes:

```ruby
    def create_transfer_request
      if on_behalf_of.present?
        ContentDepositorChangeEventJob.perform_later(self,
                                                     'sample')
      end
    end
```

and it emits a new warning:
```
Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
```

Ideally the `MultilineIfModifier` would detect that it is at the end of a function and autocorrect with a guard clause instead.

```ruby
    def create_transfer_request
      return unless on_behalf_of.present?
      ContentDepositorChangeEventJob.perform_later(self,
                                                   'sample')
    end
```

**Comment by mikegee** [comment] 2016-12-02 12:12
This is basically a dupe of https://github.com/bbatsov/rubocop/issues/3709, but your example code and suggestion are very helpful.

**Comment by madwort** [comment] 2016-12-05 10:00
I think it would make more sense to add an auto-correct to the GuardClause cop than to attempt to add more complexity to the MultilineIfModifier cop.

**Comment by EdwinRozario** [comment] 2017-11-26 22:05
This gets tricky in a Rails controller as i will have to do an early return and render

**Comment by bbatsov** [comment] 2018-09-19 15:03
Seems to me that the problem is not that big in practice and probably it's not worth making the cops more complex just to simply the auto-correct steps. 

I'm open to concrete PRs that improve the current situation, but for now I'll just close this.

**Closed by bbatsov** 2018-09-19 15:03 UTC
