### ISSUE TITLE
Lint/RedundantDirGlobSort cop Responds with undefined method for Nil class

### ISSUE THREAD

**Issue by ninp0** [rubocop-hq/rubocop#9348] opened 2021-01-07 21:49 UTC
```
$ rubocop -d
An error occurred while Lint/RedundantDirGlobSort cop was inspecting /opt/csi/lib/csi.rb:22:4.
undefined method `const_type?' for nil:NilClass
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/lint/redundant_dir_glob_sort.rb:37:in `on_send'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:136:in `public_send'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:136:in `block (2 levels) in trigger_restricted_cops'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:135:in `block in trigger_restricted_cops'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:134:in `each'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:134:in `trigger_restricted_cops'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:161:in `on_defs'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:71:in `on_defs'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:156:in `each'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:156:in `on_send'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:71:in `on_send'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `each'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:138:in `on_while'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `each'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/team.rb:157:in `investigate_partial'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cop/team.rb:83:in `investigate'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:315:in `inspect_file'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:286:in `loop'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:131:in `file_offenses'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:122:in `process_file'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:100:in `each'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:100:in `reduce'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:86:in `inspect_files'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/runner.rb:47:in `run'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli.rb:65:in `run_command'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli.rb:72:in `execute_runners'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/lib/rubocop/cli.rb:41:in `run'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/exe/rubocop:13:in `block in <top (required)>'
/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/usr/local/rvm/gems/ruby-3.0.0@csi/gems/rubocop-1.8.0/exe/rubocop:12:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.0.0@csi/bin/rubocop:23:in `load'
/usr/local/rvm/gems/ruby-3.0.0@csi/bin/rubocop:23:in `<main>'
```
--------

## Expected behavior
Continues scanning the repo without error.

## Actual behavior

```
<snip>
An error occurred while Lint/RedundantDirGlobSort cop was inspecting /opt/csi/lib/csi.rb:22:4.
undefined method `const_type?' for nil:NilClass
</snip>
```

## Steps to reproduce the problem
```
$ git clone https://github.com/0dayinc/csi
$ rubocop -d
```

## RuboCop version
```
$ rubocop -V
1.8.0 (using Parser 3.0.0.0, rubocop-ast 1.4.0, running on ruby 3.0.0 x86_64-darwin19)
```

**Comment by koic** [comment] 2021-01-08 04:07
The issue is a dup with #9342 and resolved by #9344. Thank you for you feedback!

**Closed by koic** 2021-01-08 04:07 UTC
