### ISSUE TITLE
Style/SymbolProc auto-correct issue with cancancan

### ISSUE THREAD

**Issue by shaicoleman** [rubocop-hq/rubocop#6913] opened 2019-04-09 10:45 UTC
When I run: `rubocop --auto-correct --only Style/SymbolProc app/models/ability.rb`

It corrects from:
```
      can %i[list manage], Schedule do |schedule|
        schedule.guarantee?
      end
```

To:
```
      can %i[list manage], Schedule, &:guarantee?
```

Afterwards my specs break.

## RuboCop version
`0.67.2 (using Parser 2.6.2.1, running on ruby 2.6.2 x86_64-linux)`

**Comment by rrosenblum** [comment] 2019-04-25 19:21
This is a duplicate of #3071. Essentially, this is likely an issue with `cancancan` not implementing `to_proc` properly. It might be able to fix this issue inside of `cancancan`. It looks like the previous solution was to mark auto-correction for this cop as unsafe. I don't think there is anything else that we can do to account for this in RuboCop.

**Comment by Drenmi** [comment] 2019-04-26 02:10
> Essentially, this is likely an issue with cancancan not implementing to_proc properly. It might be able to fix this issue inside of cancancan. It looks like the previous solution was to mark auto-correction for this cop as unsafe.

Yes. This crops up all the time, because Rails does some unconventional handling in Rails. I marked the cop as unsafe for autocorrect in 0.64 (#6730).

**Closed by Drenmi** 2019-04-26 02:10 UTC
