### ISSUE TITLE
RescuedExceptionsVariableName don't understand methods-as-rescue

### ISSUE THREAD

**Issue by weppos** [rubocop-hq/rubocop#6912] opened 2019-04-09 08:44 UTC
In Ruby you can call a method in the rescue statement, and have it return an exception.

```ruby
module Errors
  def self.errors_matching_code(code)
    m = Module.new
    (class << m; self; end).instance_eval do
      define_method(:===, ->(e) { e.respond_to?(:code?) && e.code?(code) })
    end
    m
  end
end

begin
    ...
rescue Errors.errors_matching_code(1)
    ...
end
```

Rubocop 0.67.2 is currently unable to properly handle this case.

```
Naming/RescuedExceptionsVariableName: Use e instead of Errors.errors_matching_code(ERROR_CODE_SYSTEM_FAILEDUPDATE).
  rescue Errors.errors_matching_code(ERROR_CODE_SYSTEM_FAILEDUPDATE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bquorning** [comment] 2019-04-25 09:53
I think this is a duplicate of #6907.

**Closed** 2019-04-26 02:05 UTC
Labels: duplicate
