### ISSUE TITLE
Crash on UselessAssignment

### ISSUE THREAD

**Issue by zub** [rubocop-hq/rubocop#7997] opened 2020-05-20 08:01 UTC
When trunning the UselessAssignment lint, I got a crash. It seems rubocop will crash due to any unused variable from my isolated testing.

This happens when RuboCop is run though Homebrew, ref. homebrew/brew#7608. I can not reproduce the same behaviour though calling rubocop directly, however the homebrew maintainers have isolated the issue to inside the rubocop gem.

--------

## Expected behavior

As normal.

## Actual behavior

Crash:

<pre>
configuration from /usr/local/Homebrew/Library/.rubocop.yml
Inheriting configuration from /usr/local/Homebrew/Library/.rubocop_shared.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-performance-1.5.2/config/default.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-performance-1.5.2/config/default.yml
Default configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/config/default.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rspec-1.39.0/config/default.yml
configuration from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rspec-1.39.0/config/default.yml
Running parallel inspection
An error occurred while VariableForce cop was inspecting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crash-rubocop.rb.
uninitialized constant DidYouMean::SpellChecker
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:18:in `find_similar_names'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:9:in `find_similar_name'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:97:in `similar_name_message'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:77:in `message_specification'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:68:in `message_for_useless_assignment'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:52:in `block in check_for_unused_assignments'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:49:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:49:in `check_for_unused_assignments'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:42:in `block in after_leaving_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:41:in `each_value'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/lint/useless_assignment.rb:41:in `after_leaving_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:33:in `block in run_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:30:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/force.rb:30:in `run_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:400:in `block (2 levels) in <class:VariableForce>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force/variable_table.rb:17:in `invoke_hook'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force/variable_table.rb:36:in `pop_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:96:in `inspect_variables_in_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:296:in `process_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:86:in `process_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:103:in `block in process_children'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:187:in `block in each_child_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:184:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/ast/node.rb:184:in `each_child_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:100:in `process_children'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:95:in `inspect_variables_in_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:296:in `process_scope'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:86:in `process_node'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/variable_force.rb:80:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:108:in `block (2 levels) in invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:107:in `block in invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:104:in `invoke_custom_processing'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/commissioner.rb:43:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:124:in `investigate'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:112:in `offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:301:in `inspect_file'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:249:in `block in do_inspection_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:281:in `block in iterate_until_no_changes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:274:in `loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:274:in `iterate_until_no_changes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:245:in `do_inspection_loop'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:124:in `block in file_offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:148:in `file_offense_cache'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:122:in `file_offenses'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:509:in `call_with_index'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:471:in `process_incoming_jobs'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:453:in `block in worker'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:444:in `fork'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:444:in `worker'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:435:in `block in create_workers'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:434:in `create_workers'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:373:in `work_in_processes'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:277:in `map'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.19.1/lib/parallel.rb:227:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:59:in `warm_cache'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/runner.rb:38:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/command.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli/environment.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:65:in `run_command'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:72:in `execute_runners'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/cli.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/exe/rubocop:12:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/rubocop:23:in `load'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/rubocop:23:in `<main>'
Scanning /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crash-rubocop.rb
</pre>

## Steps to reproduce the problem

The code
```ruby
class CrashStyle < Formula
  def install
    some_variable = "crash"
  end
end
```
crashes due to the unused variable.

## RuboCop version

```
$ rubocop -V
0.83.0 (using Parser 2.7.1.2, running on ruby 2.7.1 x86_64-darwin18)
```

**Comment by koic** [comment] 2020-05-20 08:19
Maybe dup with #7979.

**Comment by brianlow** [comment] 2020-05-25 16:11
In case it helps, I see as well when installed via bundler (not homebrew), 0.84.0

```
$ rubocop -d myfile.rb
...
An error occurred while VariableForce cop was inspecting /Users/brian/myproject/myfile.rb.
uninitialized constant DidYouMean::SpellChecker
/Users/brian/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.84.0/lib/rubocop/name_similarity.rb:18:in `find_similar_names'
/Users/brian/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.84.0/lib/rubocop/name_similarity.rb:9:in `find_similar_name'
/Users/brian/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.84.0/lib/rubocop/cop/lint/useless_assignment.rb:97:in `similar_name_message'
/Users/brian/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.84.0/lib/rubocop/cop/lint/useless_assignment.rb:77:in `message_specification'
...
```

**Comment by brianlow** [comment] 2020-05-25 16:31
Perhaps ruby version and/or asdf.

In [ruby 2.6.3 did_you_mean is a "bundled" gem](https://stdgems.org/2.6.3/) and in [ruby 2.7.0 it is a "standard gem"](https://stdgems.org/2.7.0/). 

I have ruby 2.6.3 installed via asdf version manager:
```
$ gem info did_you_mean

*** LOCAL GEMS ***

$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
```

**Comment by bquorning** [comment] 2020-05-27 13:10
Closing as duplicate of #7979.

**Closed by bquorning** 2020-05-27 13:10 UTC
Labels: duplicate
