### ISSUE TITLE
Regression in 0.91.0 in Layout/RescueEnsureAlignment

### ISSUE THREAD

**Issue by jcoyne** [rubocop-hq/rubocop#8760] opened 2020-09-21 16:49 UTC
Previously this was valid:

```
    request_model = begin
                      'something'
                    rescue StandardError => e
                      return 'other stuff'
                    end
```

But now after upgrading to 0.91.0 this trips: `Layout/RescueEnsureAlignment`

Possibly due to changes https://github.com/rubocop-hq/rubocop/pull/8628/files#diff-e066e4a443e8fb75fe62f10fef9c6866R24

**Comment by koic** [comment] 2020-09-21 17:53
This issue is a dup with #8710 and resolved by #8719. Please wait a moment for the next release. Thank you for the feedback.

**Closed by koic** 2020-09-21 17:53 UTC
Labels: bug, duplicate

**Comment by mvz** [comment] 2020-09-24 08:29
I'm still seeing this with RuboCop 0.91.1.

**Comment by koic** [comment] 2020-09-24 09:17
@mvz I cannot reproduce this issue with RuboCop 0.91.1. Can you provide the issue code?

**Comment by mvz** [comment] 2020-09-25 08:02
@koic here's a simple reproduction:

*foo.rb:*
```ruby
# frozen_string_literal: true

foo = begin
        bar
      rescue StandardError
        baz
      end

qux foo
```

*.rubocop.yml:*
```yaml
AllCops:
  NewCops: enable
```

*Output:*
```
$ rubocop foo.rb
Inspecting 1 file
W

Offenses:

foo.rb:5:7: C: Layout/RescueEnsureAlignment: rescue at 5, 6 is not aligned with foo = begin at 3, 0.
      rescue StandardError
      ^^^^^^
foo.rb:7:7: W: Layout/BeginEndAlignment: end at 7, 6 is not aligned with foo = begin at 3, 0.
      end
      ^^^

1 file inspected, 2 offenses detected, 2 offenses auto-correctable
```

*RuboCop version info:*
```
0.91.1 (using Parser 2.7.1.5, rubocop-ast 0.5.0, running on ruby 2.7.1 x86_64-linux)
```

**Comment by mvz** [comment] 2020-09-25 08:04
I get the same result with the following `.rubocop.yml`:

```yaml
Layout/BeginEndAlignment:
  Enabled: true
```

**Comment by koic** [comment] 2020-09-25 17:51
@mvz I get it. The default configuration for `Layout/BeginEndAlignment` is `EnforcedStyleAlignWith: start_of_line`. You can get the expected behavior by setting alternative `EnforcedStyleAlignWith: begin` to your .rubocop.yml.

```yaml
Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: begin
```

https://docs.rubocop.org/rubocop/0.92/cops_layout.html#layoutbeginendalignment

**Comment by mvz** [comment] 2020-09-26 09:20
@koic Thanks for looking into this. Changing the EnforcedStyleAlignWith to `begin` works for me!

I'm a little confused by the difference in default settings between Layout/BeginEndAlignment and Layout/EndAlignment, but that's another issue.
