### ISSUE TITLE
[Style/BlockDelimiters] Prefer{...}overdo...endfor single-line blocks. Error.

### ISSUE THREAD

**Issue by ghost** [rubocop-hq/rubocop#5346] opened 2017-12-28 18:01 UTC
I have this code in a .rb Class file:

`field :user, Types::UserType do resolve ->(_obj, _args, ctx) { ctx[:user] } end`

what I need is to remove `do` and `end` from the single line using, I think, the `{}`.

`[Style/BlockDelimiters] Prefer `{...}` over `do...end` for single-line blocks.`

But I don't understand why it throws this error:

```
[ruby] syntax error, unexpected '{', expecting '('
[ruby] syntax error, unexpected '}', expecting keyword_end
```

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x64-mingw32)
```

**Comment by bbatsov** [comment] 2018-01-01 09:43
Is this also a problem in the latest stable release?

**Comment by Drenmi** [comment] 2018-01-02 17:51
Yep. Just reproduced this on latest `master`.

**Comment by koic** [comment] 2018-08-01 06:17
I cannot reproduce this Issue and the reporter is already [a ghost user](https://help.github.com/articles/deleting-your-user-account/), I will close this issue.

**Closed by koic** 2018-08-01 06:17 UTC
