### ISSUE TITLE
Wildcard excludes do not work if running within Git Bash

### ISSUE THREAD

**Issue by amyspark** [rubocop-hq/rubocop#7190] opened 2019-06-30 23:47 UTC
Hey all,

I've run into a bug when using Rubocop with bash (Git Bash) under Visual Studio Code.

This is the relevant portion of .rubocop.yml:

```yaml
require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'app/views/**/*'
    - 'bin/*'
    - 'config/initializers/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'storage/**/*'
    - 'vendor/**/*'

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: true

Layout/AlignParameters:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/EndAlignment:
  AutoCorrect: true
  EnforcedStyleAlignWith: start_of_line

Layout/IndentFirstArgument:
  Enabled: true

Layout/IndentFirstArrayElement:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: true

Layout/IndentFirstParameter:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Metrics/BlockLength:
  Max: 80
  ExcludedMethods:
    - RSpec.describe

Metrics/LineLength:
  AutoCorrect: true
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Rails/FilePath:
  EnforcedStyle: slashes

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/MultipleExpectations:
  Max: 2

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'config/application.rb'
    - 'db/migrate/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
```

## Expected behavior

When running `rubocop -a`, it doesn't check excluded files.

## Actual behavior

Rubocop checks all paths including the excluded entries:
```
$ rubocop -a
Inspecting 112 files
............................................C........CCCCCCCCCCC.................................C............C.

Offenses:

config/application.rb:23:3: C: Style/Documentation: Missing top-level class documentation comment.
  class Application < Rails::Application
  ^^^^^
db/migrate/20190606220116_create_languages.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateLanguages < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606220200_create_countries.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateCountries < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606220320_create_author_types.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateAuthorTypes < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606220834_create_project_types.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProjectTypes < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606221119_create_product_types.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProductTypes < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606221403_create_areas.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateAreas < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606221457_create_sectors.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateSectors < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606222535_create_disciplines.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateDisciplines < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190610205506_create_products.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProducts < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190612214733_create_articles.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateArticles < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190618133227_create_product_disciplines.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProductDisciplines < ActiveRecord::Migration[5.2]
^^^^^
spec/rails_helper.rb:1:1: C: [Corrected] Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
# This file is copied to spec/ when you run 'rails generate rspec:install'
^
spec/rails_helper.rb:60:101: C: Metrics/LineLength: Line is too long. [105/100]
  # start by truncating all the tables but then use the faster transaction strategy the rest of the time.
                                                                                                    ^^^^^
spec/spec_helper.rb:1:1: C: [Corrected] Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
^
spec/spec_helper.rb:54:1: C: [Corrected] Style/BlockComments: Do not use block comments.
=begin ...
^^^^^^
spec/spec_helper.rb:100:1: C: [Corrected] Layout/CommentIndentation: Incorrect indentation detected (column 0 instead of 2).
#   Kernel.srand config.seed
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

112 files inspected, 17 offenses detected, 4 offenses corrected
```

This still happens when running Rubocop through a CMD instance (Git Bash -> `cmd` -> `rubocop -a`), so I believe there's a path construction issue somewhere.

## Steps to reproduce the problem

1. Install Rubocop and Git Bash.
2. Configure VS Code to use Git Bash's `bash` by setting `terminal.integrated.shell.windows` to  `d:\\Program Files\\Git\\bin\\bash.exe`.
3. Set up a project with excluded paths. Make sure the excluded paths have issues.
4. Run Rubocop.

## RuboCop version

`0.71.0 (using Parser 2.6.3.0, running on ruby 2.5.5 x64-mingw32)`

**Comment by jonas054** [comment] 2019-07-07 19:00
> 4. Run Rubocop.

This step is unclear to me. What do I do, exactly?

**Comment by amyspark** [comment] 2019-07-09 22:13
Apologies @jonas054 ! By "running Rubocop", I meant the following steps. It's probably way excessive, but it will help match my project layout.

1. Set up a Rails project with `rails new test --api -T`.
2. In the Gemfile, add `gem rails-rspec`. Run `bundle` and then `rails rspec:install`.
3. Copy the `.rubocop.yml` file I've attached in this issue.
3. Run  `rubocop -a` on the project folder.

As is, it will throw errors in the `spec` folder, which should not happen. It's also the same if you add migrations,  Rubocop wants me to document them even though I've explicitly excluded the folder.

**Comment by jonas054** [comment] 2019-07-15 11:23
I have not been able to reproduce the problem. I think we need a more minimal reproduction description:

- a minimal `.rubocop.yml`
- can we boil it down to a single file, e.g. `config/application.rb`?
- does it occur with `--only Style/Documentation`?
- is it only with `-a`?
- does it occur only in VS Code or can it be reproduced just running in a Git Bash window?

You said `rails-rspec`, but meant `rubocop-rspec`, right?

**Comment by amyspark** [comment] 2019-07-16 19:18
Hey @jonas054 , I'll reply on each point.

> a minimal .rubocop.yml

I can't minimize it, as it will introduce additional noise on the output.

> can we boil it down to a single file, e.g. config/application.rb?

I've trimmed it down to a few relevant files (one per folder) along with their subordinate `.rubocop.yml` files.

> does it occur with --only Style/Documentation?

Yes.

> is it only with -a?

No, `rubocop` and  `rubocop -a` fail in the same way.

> does it occur only in VS Code or can it be reproduced just running in a Git Bash window?

Only in VS Code, and from my experience, only when:

* using a workspace (ie more than one opened folder in the same window)
* calling the integrated terminal
* when Code asks you to select the folder, choosing it *and not changing working directory*

As soon as you change  `CWD`, the error is gone.

> You said rails-rspec, but meant rubocop-rspec, right?

Yes, my bad.

As for the reduced test case, you'll find it here -- https://github.com/amyspark/rubocop-vs-code-bug . You should be able to reproduce this by loading it to a VS Code workspace and running `rubocop` on the folder.

**Comment by jonas054** [comment] 2019-07-19 17:00
Thanks for the detailed description! Using that example project I was able to reprocude the problem in VS Code. I got the squiggly line under that `class` keyword in `application.rb` and the tooltip offense report from `Style/Documentation`.

But I have not been able (just as you hinted) to reproduce it in a shell. Not in Git Bash and not in CMD. This leads me to believe that the problem lies in [vscode-ruby-rubocop](https://github.com/misogi/vscode-ruby-rubocop) and should be reported there.

Turning on Developer Tools in the Help menu of VS Code, I saw the following log message:
```
[Extension Host] rubocop.bat -a -f simple -c c:\Users\jonas\dev\7190\amyspark\rubocop-vs-code-bug\config\.rubocop.yml C:\Users\jonas\AppData\Local\Temp\rubocopRN1fb0\tmp.rb
```
If RuboCop is run like that, excludes are not going to work. The file name becomes something different when copying to a temporary file, and the exclude functionality depends on the file name.

Implementing a safe auto-correct from within an IDE may require some new feature in RuboCop. I don't have a solution ready, but I'm sure we can make it work.

I'm closing the issue for the reasons metioned above. Let me know if you don't agree.

**Comment by amyspark** [comment] 2019-07-19 17:13
Hey @jonas054 ,

Glad to see you could reproduce it! However,

> But I have not been able (just as you hinted) to reproduce it in a shell. Not in Git Bash and not in CMD. This leads me to believe that the problem lies in vscode-ruby-rubocop and should be reported there.

I **do not** use any Ruby-related extensions in my VS Code installation. I only run Rubocop from within the integrated terminal, with `terminal.integrated.shell.windows` pointing to `"d:\\Program Files\\Git\\bin\\bash.exe"`.

Git Bash itself works correctly, it's only in their integrated terminal that this bug appears.

**Comment by jonas054** [comment] 2019-07-21 07:45
I think I finally managed to reproduce _your_ problem as well. 

I also noticed the following behavior:

```console
jonas@LAPTOP-A32CA59G MINGW64 ~/dev/7190/amyspark/rubocop-vs-code-bug (master)
$ ruby -e 'puts Dir.pwd'
c:/Users/jonas/dev/7190/amyspark/rubocop-vs-code-bug

jonas@LAPTOP-A32CA59G MINGW64 ~/dev/7190/amyspark/rubocop-vs-code-bug (master)
$ cd .

jonas@LAPTOP-A32CA59G MINGW64 ~/dev/7190/amyspark/rubocop-vs-code-bug (master)
$ ruby -e 'puts Dir.pwd'
C:/Users/jonas/dev/7190/amyspark/rubocop-vs-code-bug
```

See how the `cd .` changes the drive letter to upper case? This is what trips up RuboCop, and I think the best solution is if we handle lower case drive letters as well as upper case. A change is needed in `PathUtil#absolute?`. I'll submit a PR.

**Comment by amyspark** [comment] 2019-07-21 18:54
I did a bit more digging, and this seems to be a known issue when running shells inside VS Code: microsoft/vscode#9448, microsoft/vscode#45760, microsoft/vscode#70004 .

**Closed** 2019-07-23 05:58 UTC
